### ISSUE TITLE
manca una "guida"

### ISSUE THREAD

**Issue by albertograva** [bettellam/CTRN_VENETO#1]
Ciao! 
non riesco a capire come provare a usare la vestizione delle CTRN.
Riusciresti a descrivere meglio come si fa?

grazie mille

**Comment by bettellam** [comment]
Ciao Alberto,
è solo lo spazio creato in github.
Non ho ancora caricato niente, un singolo gpkg.
Comunque ho pronti tutti i gpkg dei 5000 veneto in GB ovest e etrf2000.
Ci sarà un apposito script per caricarli in automatico sia in BW e Colore
con tutte le etichette già formattate.
Sono fuori adesso, vedo di anticiparti il PDF di presentazione del lavoro.
A presto.
Ciao

Il Mer 22 Nov 2023, 10:53 Alberto Grava ***@***.***> ha
scritto:

**Comment by albertograva** [comment]
si tranquillo era pura curiosità!

**Comment by bettellam** [comment]
Completato Caricamento dati
